### ISSUE TITLE
problem connecting

### ISSUE THREAD

**Issue by mose** [strangeglyph/pithos#1]
hi

I wanted to try this code, and had to manually install ruamel.yaml, sqlachemy and discord.py for it to run. But now I'm not sure I installed the right versions, at first run after filling up the configuration file I get

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 255, in _run_event
    await coro(*args, **kwargs)
  File "/home/mose/projects/pithos/bot.py", line 306, in on_ready
    for server in self.servers:
AttributeError: 'PithosClient' object has no attribute 'servers'
```

(installed discord.py is 1.0.1, I tried before with discord but that was spitting out errors)

Any idea on how to solve this?

**Comment by domi41** [comment]
The `Pipfile.lock` has the deps. https://pipenv.readthedocs.io/en/latest/

Not sure if `pip install -p` already works…

**Comment by strangeglyph** [comment]
`pipenv install` should give you the required dependencies. Aftwards, try `pipenv run python main.py` to run the bot.

**Comment by strangeglyph** [comment]
Hey, I just wanted to check in whether the problems were resolved?
